site_name: AWS IATK
site_description: AWS IATK
site_author: Amazon Web Services
repo_url: https://github.com/awslabs/aws-iatk
edit_uri: edit/develop/docs

nav:
  - AWS IATK Overview:
      - index.md
      - Tutorial: 
        - tutorial/index.md
        - Examples:
          - Retrieving information from a deployed CloudFormation Stack: tutorial/examples/retrieve_cfn_info.md
          - Testing EventBridge Event Bus with Listener: tutorial/examples/eb_testing.md
          - Testing with X-Ray Traces: tutorial/examples/xray_testing.md
          - Generate Mock Events: tutorial/examples/generate_mock_events.md
      - References:
        - Python API reference: api/python" target="_blank
      - Contributing:
        - Development environment: contributing/setup.md
        - Your first contribution: contributing/getting_started.md
        - Conventions: contributing/conventions.md
      - Code of Conduct: code_of_conduct.md
      - Changelog: https://github.com/awslabs/aws-iatk/releases
      - Security: security.md
      
theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
  logo: media/aws-logo-light.svg
  favicon: media/aws-logo-light.svg
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - abbr
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list

copyright: Copyright &copy; 2023 Amazon Web Services

plugins:
  - git-revision-date
  - search

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/extra.js

extra:
  version:
    provider: mike
    default: latest