AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Test Application for GetTraceTree (Lambda -> SQS -> Lambda)

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  MySQSQueue:
    Type: AWS::SQS::Queue

  ProducerA:
    Type: AWS::Serverless::Function
    Connectors:
      ToSQS:
        Properties:
          Destination:
            QueueUrl: !Ref MySQSQueue
            Type: AWS::SQS::Queue
            Arn: !GetAtt MySQSQueue.Arn
          Permissions:
            - Write
    Properties:
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref MySQSQueue
      InlineCode: |
        import boto3, os
        sqs_client = boto3.client("sqs")
        def handler(event, context):
            sqs_client.send_message(
                QueueUrl=os.getenv("SQS_QUEUE_URL"),
                MessageBody="hello, world!",
            )
            return True
      Runtime: python3.11
      Handler: index.handler

  ConsumerA:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        def handler(event, context):
            print(event.get("Records"))
            return {"statusCode": 200, "body": "hello, world!"}
      Runtime: python3.11
      Handler: index.handler
      Events:
        SQSBatch:
          Type: SQS
          Properties:
            Queue: !GetAtt MySQSQueue.Arn
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: MyLambdaState
        States:
          MyLambdaState:
            Type: Task
            Resource: !GetAtt ConsumerA.Arn
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ConsumerA
      Tracing:
        Enabled: true
      
Outputs:
  ProducerFunctionName:
    Value: !Ref ProducerA
  ApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  StateMachineArn:
    Value: !Ref MyStateMachine
