name: Bug report
description: Report a reproducible bug to help us improve
title: "Bug: TITLE"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report. Please add as much information as possible to help us reproduce, and remove any potential sensitive data.

  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      description: Please share details on the behaviour you expected
    validations:
      required: true
  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour
      description: Please share details on the current issue
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code snippet
      description: Please share a code snippet to help us reproduce the issue
      render: python
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If known, please suggest a potential resolution
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Please share how we might be able to reproduce this issue
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version used
      placeholder: "latest"
      value: latest
    validations:
      required: true