name: "Integration Tests"

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: "the ref (branch, commit sha, or tag) to run tests against"
      GO_VERSION:
        required: false
        type: string
        default: "1.20"
        description: "Go version for building IATK binary"

env:
  GO_VERSION: "1.20"

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: integ-tests
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: "us-east-1"
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
        with:
          ref: ${{ inputs.ref }}

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: "3.8"

      - uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          role-to-assume: ${{ secrets.CI_IAM_ROLE_ARN }}
          role-session-name: CiIntegTests
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Run integration tests
        run: make integ-test

      - name: Setup Python Client with dev dependencies
        working-directory: "python-client"
        run: |
          make copy-service-source-for-sdist
          make init

      - name: Run Python Client end-to-end tests
        working-directory: "python-client"
        run: |
          make integ-test
          